logging:
  level:
    org.springframework.security.saml2: DEBUG
    org.opensaml: DEBUG
spring:
  application:
    name: spring-as-saml-sp
  security:
    user:
      password: test123
    saml2:
      relyingparty:
        registration:
          liferay-idp:
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
            assertingparty:
              metadata-uri: "classpath:metadata/metadata-idp.xml"
